#pragma config(ProgramType, NonCompetition)
#pragma config(Motor,  port1,           rMotor,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           lMotor,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           iMotor1,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           iMotor2,       tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
Robotix w/ VEX PIC - Tank Drive
Author: Sam Rice
Date Created: 20160714
Date Modified: 20160715
Version: 0.2
https://github.com/RoboticRice/LegacyVEX/

Description: This is a simple tank drive program to test out using the 2-wire
	motor controller with the spliced cable on Robotix High-Speed motors.

Configuration:

				(Front of Robot)
 _____________________________
|                             |
|                             |
|            _____            |
|           | PIC |           |
|           |_____|           |
|                             |
O lMotor               rMotor O
|                             |
|_____________________________|

	(VEX PIC)
*Motors
Port1 = rMotor
Port2 = lMotor
Port7 = iMotor1 //Used for debugging puropses
Port8 = iMotor2 //Used for debugging puropses

	(Joystick)
Ch1 (Right Analog Stick, Left-Right)
Ch2 (Right Analog Stick, Up-Down)
Ch3 (Left Analog Stick, Up-Down)
Ch4 (Left Analog Stick, Left-Right)
Ch5 (Back Buttons, Left Hand)
Ch6 (Back Buttons, Right Hand)

	(Controls)
Ch2 = rMotor Forward/Backward
Ch3 = lMotor Forward/Backward
Ch5 = Incrament iMotor speed by 32
Ch6 = Incrament iMotor speed by 8

Additional Notes:
* The "bVexAutonomousMode = false;" is needed to open up communication so
  that the VEX can talk to the radio transmitter.
* While "bVexAutonomousMode" is false, the Joystick MUST be connected and
	turned on in order for the program to run.
* iSpeed is an incramental speed for debugging the capabilities of the
	Robotix motors. Ports 7 & 8 should NOT be plugged in during normal
	operation.
*************************************************************************/

task main()
{
	//Run Once on Init Code Block
	int rSpeed = 0;
	int lSpeed = 0;
	int iSpeed = 0;
	bool btnReleased = true;
	bVexAutonomousMode = false;			//Activates Remote Control Mode
	while (true)									  //Creates and infinite loop
	{
		//Main Continuous Code Block
		rSpeed = vexRT[Ch2];
		lSpeed = vexRT[Ch3];
		motor[rMotor] = rSpeed;
		motor[lMotor] = lSpeed;
		//Incramental Section:
		if (btnReleased) {
			btnReleased = false;
			if (vexRT[Ch5] >= 1) {
				//Increase by 32
				iSpeed += 32;
			} else if (vexRT[Ch5] <= -1) {
				//Decrease by 32
				iSpeed -= 32;
			} else if (vexRT[Ch6] >= 1) {
				//Increase by 8
				iSpeed += 8;
			} else if (vexRT[Ch6] <= -1) {
				//Decrease by 8
				iSpeed -= 8;
			} else {
				btnReleased = true;
			}
		} else if ((vexRT[Ch5] == 0)&&(vexRT[Ch6] == 0)) {
				btnReleased = true;
		}
		motor[iMotor1] = iSpeed;
		motor[iMotor2] = iSpeed;
		//writeDebugStreamLine("iSpeed = " + iSpeed);
	}
}
