#pragma config(ProgramType, NonCompetition)
#pragma config(Motor,  port1,           eyeBalls,      tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
Animatronic Head with Moving Eyes
Sam Rice - 20210320
https://github.com/RoboticRice/LegacyVEX/

Description: This program is under development. It is intended to control
the Eye movement of an animatronic.

Additional Notes:
* The "bVexAutonomousMode = false;" is needed to open up communication so
  that the VEX can talk to the radio transmitter. We aren't driving this
  model via remote, so I have set this to "true"
* Need to add Eye Lids movement at a later date.
*************************************************************************/

#define CENTER 0
#define RMAX -100
#define LMAX 100

task main()
{
	//Run Once on Init Code Block
	bVexAutonomousMode = true;//Disables Remote Control Mode

	int position = 0;
	int increase = 1; //1 or -1 to control direction
	int pauseTime = 200; //I want to make this NOT a wait function moving forward.

	while (true)//Creates and infinite loop
	{
		//Main Continuous Code Block
		if (position > LMAX)
		{
			increase = -1; //decrease
			wait10Msec(pauseTime);
		}
		else if (position < RMAX)
		{
			increase = 1; //increase
			wait10Msec(pauseTime);
		}
		else if (position == CENTER)
			wait10Msec(pauseTime);

		position = position + increase;

		motor[eyeBalls] = position;

		wait1Msec(2);
	}
}
