#pragma config(ProgramType, NonCompetition)
#pragma config(Motor,  port1,           mtrLFT,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           mtrRGT,        tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "TankDrive.h"
/*************************************************************************
VEX PIC - Demo Program for TankDrive.h

Description:

Configuration:

Additional Notes:
*************************************************************************/

task main()
{
	bVexAutonomousMode = false;			//Activates Remote Control Mode
	while(true)
	{
		TankDrive(127);
	}
}
