#pragma config(ProgramType, NonCompetition)
#pragma config(Motor,  port1,            ,             tmotorServoStandard, openLoop)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex269, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
Name of Platform - Name of Program
Author - YYYYMMDD
https://github.com/RoboticRice/LegacyVEX/

Description: This should be a description

Configuration: The physical configuration of compenents in relation to the
vex PIC.

Additional Notes:
* The "bVexAutonomousMode = false;" is needed to open up communication so
  that the VEX can talk to the radio transmitter.
* Other notes.
*************************************************************************/

task main()
{
	//Run Once on Init Code Block
	int dogSpeed =  127/3;
	int upSpeed  =  127/4;
	int dwnSpeed = -127/2;
	int pntSpeed = upSpeed;
	bVexAutonomousMode = true;//false;			//Activates Remote Control Mode when false
	while (true)													  //Creates and infinite loop
	{
		//Main Continuous Code Block
		motor[port1] = dogSpeed; //BroomDog
		motor[port2] = pntSpeed; //2 of Clubs
		motor[port3] = pntSpeed; //Ace of Clubs
		motor[port4] = 127/2;	//BreadnButterFlies
		dogSpeed = dogSpeed*-1;//vexRT[Ch1];
		if (pntSpeed == upSpeed) pntSpeed = dwnSpeed;
		else pntSpeed = upSpeed;
		waitInMilliseconds(1000);//300);
		motor[port1] = 0;
		waitInMilliseconds(50);
	}
}
