#pragma config(ProgramType, NonCompetition)
#pragma config(Motor,  port1,           vexMTR,        tmotorServoContinuousRotation, openLoop) //All motor types work!!!
#pragma config(Motor,  port2,           vexSVO,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           vex269,        tmotorVex269, openLoop)
#pragma config(Motor,  port4,           vex393,        tmotorVex393, openLoop)
#pragma config(Motor,  port5,           vexFST,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           vexMR2,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
VEX - Dual Joystick Control

Description: This program allows the user to remotely control their robot
using the vertical axis of the Radio Control Transmitter. An infinite
while loop is used to continually update the power level of the motor
ports to the values provided by the transmitter.

Configuration: This program is written to work with the Squarebot model.
Right Motor - port2
Left	Motor - port3
RF Receiver - Rx1

Additional Notes:
-	The "bMotorReflected[port2] = 1;" is needed with the Squarebot model,
but may not be needed for all robot configurations.
-	Each motor is controlled by a separate joystick on the transmitter.
-	The "bVexAutonomousMode = false;" is needed to open up communication so
that the VEX can receive signals.
-	Parameters and information for vexRT:
Ch1 = Right Joystick X-axis
Full Right = 127
Middle     = 0
Full Left  = -127
Ch2 = Right Joystick Y-axis
Full Up    = 127
Middle     = 0
Full Down  = -127
Ch3 = Left Joystick Y-axis
Full Up    = 127
Middle     = 0
Full Down  = -127
Ch4 = Left Joystick X-axis
Full Right = 127
Middle     = 0
Full Left  = -127
Ch5 = Rear Left Buttons
None Pressed    = 0
Top Pressed     = 127
Down Pressed  	= -127
Both Pressed		= 0
Ch6 = Rear Right Buttons
None Pressed    = 0
Top Pressed     = 127
Down Pressed  	= -127
Both Pressed		= 0
*************************************************************************/

task main()
{
	int maxSpd = 127;
	//int maxBck = maxSpeed*-1;
	bVexAutonomousMode = false;			//Activates Remote Control Mode
	while (1 == 1)									  //Creates and infinite loop
	{
		//placeHolder = vexRT(Ch1); //This is how you call the RT
		motor[port1] = maxSpd;
		motor[port2] = maxSpd;
		motor[port3] = maxSpd;
		motor[port4] = maxSpd;
		motor[port5] = maxSpd;
		motor[port6] = maxSpd;
		motor[port7] = maxSpd;
		motor[port8] = maxSpd;
	}
}
