#pragma config(ProgramType, NonCompetition)
#pragma config(Motor,  port1,           vexMTR,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
Name of Platform - Name of Program
Author - YYYYMMDD
https://github.com/RoboticRice/LegacyVEX/

Description: This should be a description

Configuration: The physical configuration of compenents in relation to the
vex PIC.

Additional Notes:
* The "bVexAutonomousMode = false;" is needed to open up communication so
  that the VEX can talk to the radio transmitter.
* Other notes.
*************************************************************************/

task main()
{
	//Run Once on Init Code Block
	bVexAutonomousMode = false;			//Activates Remote Control Mode
	while (true)									  //Creates and infinite loop
	{
		//Main Continuous Code Block
	}
}
