#pragma config(ProgramType, NonCompetition)
#pragma config(Motor,  port1,            ,             tmotorServoStandard, openLoop)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex269, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
Name of Platform - Name of Program
Author - YYYYMMDD
https://github.com/RoboticRice/LegacyVEX/

Description: This should be a description

Configuration: The physical configuration of compenents in relation to the
vex PIC.

Additional Notes:
* The "bVexAutonomousMode = false;" is needed to open up communication so
  that the VEX can talk to the radio transmitter.
* Other notes.
*************************************************************************/

task main()
{
	//Run Once on Init Code Block
	int speed = 0;
	bVexAutonomousMode = false;			//Activates Remote Control Mode
	while (true)									  //Creates and infinite loop
	{
		//Main Continuous Code Block
		speed = vexRT[Ch1];
		motor[port1] = speed;
		motor[port2] = speed;
		motor[port3] = speed;
		motor[port4] = speed;
		motor[port5] = speed;
		motor[port6] = speed;
		motor[port7] = speed;
		motor[port8] = 127;
	}
}
